---
title: "statistics m&m"
author: "Steven Wink"
date: "June 10, 2016"
output: word_document
---





## Image analysis 

Image analysis was performed with CellProfiler[ref] in combination with an in house developed segmentation algorithm; watershed masked clustering (WMC) [ref]. Foci counts were analysis using the FOCIpicker3D {zoiets} [ref] algorithm in ImageJ [ref]. 
The following imaging measures were used; For p53BP1 and Keap1 the number of foci was determined for each cell. For p21, p53, CHOP, XBP1, Atf4 and Nrf2 the mean intensity of the nuclei was determined for each cell. For the Btg2, BiP and Srxn1 the integrated intensity of the cytoplasm's was determined for each cell. For the model compound set the mean of the cell population was used as the final image measure. For the DILI compound set the fraction of GFP positive cells was used as the final image measure.

## Scaling and plate normalization

For model compound dataset the different imaging measures were standardized by scaling ( i.e. mean or sum of intensity measures, foci counts ), scaling was used for each plate - cell line combination;

$$ x_{\text{scaled}} = \frac{x - x_{\text{min}}}{x_{\text{max}} - x_{\text{min}}}  $$


For the DILI compound dataset the fraction of GFP positive cells was determined to increase sensitivity of the assay. A GFP positive cell was defined as minimally twice the DMSO - control background level. No scaling was used for the GFP positive fraction measures.
The total imaging time and time intervals for the different plates and replicates varied, thus for statistical analysis and plate normalization regression was performed using the 'lm' function of the 'stats' package. Natural spline regression with 6 degrees of freedom was performed using the 'ns' function of the 'splines' package. The additional linear constraints of the natural spline algorithm at the predictor boundaries allowed a stable extrapolation of the total time to equal length for all plates. 24 equidistant time points for each condition where sampled from the model and subjected to quantile normalization to equalize the distributions for each plate. 

## Statistical analysis


The quantile normalized data was subjected to statistical significance tests with the following set of formulae;

the mean over the replicates for the DMSO controls for each reporter $\text{rp}$ and time point $\text{tp}$: 

$$ \bar{x}_{\text{DMSO}}\text{(rp,tp)} = \frac{1}{\text{repl}} 
  \sum_{
    r = 1 
    }^{
    \text{repl}
    } x_{\text{DMSO}} \text{(rp, tp)} $$


The difference $\text{x_diff}$ between the DMSO means and treatments normalized with standard errors at each reporter $\text{rp}$, treatment $\text{tr}$ and time point $\text{tp}$. With the standard errors: 

$$ {x}_{\text{diff}}\text{(repl, rp, tr, tp )} = \frac{
  x - \bar{x}_{\text{DMSO}}}{
    \sqrt{\sigma_{\text{DMSO}}^{2} + \sigma_{\text{DMSO, resid}}^{2} + \sigma_{\text{tr}}^{2} + \sigma_{\text{tr, resid}}^{2}}
  } $$


The standard error over the replicates of the DMSO controls, for each reporer and time point: 

$$ \sigma_{x_{\text{DMSO}}} \text{(rp, tp )} = sd(x_{\text{DMSO}} \text{(rp, tp  ) )} $$


The standard error over the replicates , for each reporter, treatment and time point: 

$$ \sigma_{x}\text{(rp, tr, tp)}  = sd(x\text{( rp, tr, tp )} ) $$

The mean residual standard error, with $\text{resid}$ the residuals from the regression, for each replicate, reporter and treatment.
This ensures the variance from the raw data is included in the statistical analysis.

$$ \sigma_{\hat{x}\text{,resid}} \text{( repl, rp, tr)} = \sqrt( \frac{ 
    \sum\limits_{tp} ( \text{resid} \text{( repl, rp, tr )} )^2 }{
    d.f._{\text{tp}} - 1
    } )  $$  

Finally, for each replicate, reporter and treatment the mean difference over time $\text{meanDiff}$ is calculated;

$$ x_{ \text{meanDiff}} \text{( repl, rp, tr )} = \frac{ 1 }{ tp } \sum_{ tp=1 }^{ tp } x \text{( repl, rp, tr )} $$

A two sample one sided student's t-tests between the $\text{meanDiff}$ values of matched DMSO control replicates and treatment replicates was performed. A one sided test was chosen as we are only interested in positive responses with respect to our DMSO controls. To control for the p-value gained by using a one-sided test, all p-values were were multiplied by 2.

In summary, the average and standard error for each point in time of the quantile normalized values was calculated over the replicates for DMSO. The distance of the treatments to the DMSO mean at each point was determined and normalized by four standard error terms; the standard error of the treatment replicates, the DMSO replicates and the mean residual standard error of the regression analysis for the treatments and controls.
The mean difference over time was calculated, followed by a one-sided student's t-test to determine if the replicate treatment curves were significantly different in the positive direction compared to the DMSO control replicates.


## Cluster analysis
Cluster analysis was performed using the 'dist' and 'hclust' functions from the 'stats' package from the base R distribution.
For all cluster analysis the distance metric was 'euclidean' and clustering algorithm 'complete'.
The clustering of the time curve data required clustering of an extra dimension (time). All pair-wise time curve distances were computed. The mean distances per compound-compound and reporter-reporter combinations were calculated - reducint the dimensions to 2, and used as input for the clustering algorithm. 

All analysis was performed with R 3.2.3  [ref]