---
title: "norm and stats imaging data"
author: "Steven Wink"
date: "June 12, 2016"
output: html_document
---

## The functions to generate the data, perform the analysis and save the plots for presentation:
** A practical methodology to normalization and statistics of time response imaging data


```{r generate data and figures ,echo = FALSE, eval = TRUE }
setwd("C:/Users/steve_000/Documents/work/POC paper/presentation")

require( ggplot2 )
require( data.table )
require( reshape2 )
# generate data representing plate differences and difference in the dynamics of responses

# the lower replicate 1, 30 time points, till 22 hours
time_repl1 <- seq( 0.5, 22, length.out = 30 )
control_rep1 <- abs( 0.06 + 0.007 * rnorm( 30 ) )
treatlow_rep1 <- control_rep1 + control_rep1 * 0.015* time_repl1 + 0.005 * time_repl1^1.1



# the early peak
convolution_peak <-   1/( 1+  0.15*( time_repl1- 5 )^2)

treatmid_rep1 <- control_rep1 + 0.2 * convolution_peak

# the plateau response
convolution_high<-  1/( 1+  0.015*( time_repl1- 22 )^2)



treathigh_rep1 <- -0.1 + control_rep1 + 0.4*convolution_high + 0.005 * time_repl1^1.1 +  0.4*convolution_high * control_rep1 




# replicate 2, the normal response, 22 time points, till 23 hours
time_repl2 <- seq( 0.8, 23, length.out = 22 )
control_rep2 <- abs( 0.16 + 0.011 * rnorm( 22 ) )
treatlow_rep2 <- control_rep2 + control_rep2 * 0.022* time_repl2
convolution_peak <-  1/( 1+  0.15*( time_repl2- 5 )^2)

treatmid_rep2 <- control_rep2 + 0.3 * convolution_peak


convolution_high<-  1/( 1+  0.010*( time_repl2- 21 )^2)

convolution_high[ which(max(convolution_high) == convolution_high) : length( convolution_high )] <- max( convolution_high)
plot(convolution_high)

# addition of convolution term. addition of time dependent increase. and convolution multiplication term for increase in variance
treathigh_rep2 <- control_rep2 -0.5 + 1*convolution_high  + 0.005 * time_repl2^1.2 + convolution_high * control_rep2 
plot(treathigh_rep2)




# the single mega high response and high variance replicate 3, 17 time points, till 24 hours
time_repl3 <- seq( 0.8, 23, length.out = 22 )
control_rep3 <- abs( 0.2 + 0.023 * rnorm( 22 ) )
treatlow_rep3 <- control_rep3 + control_rep3 * 0.022* time_repl3
convolution_peak <-  1/( 1+  0.15*( time_repl3- 5 )^2)
treatmid_rep3 <- control_rep3+ 0.4 * convolution_peak

convolution_high<-  1/( 1+  0.010*( time_repl3- 15 )^2)

convolution_high[ which(max(convolution_high) == convolution_high) : length( convolution_high )] <- max( convolution_high)
plot(convolution_high)

# addition of convolution term. addition of time dependent increase. and convolution multiplication term for increase in variance
treathigh_rep3 <- -0.55 + control_rep3  + 1*convolution_high  + 0.005 * time_repl3^1.2 + 1*convolution_high * control_rep3 
plot(treathigh_rep3)


image_data_rep1 <- data.frame( time = time_repl1, 
                                control =  control_rep1,
                               treatlow = treatlow_rep1,
                               treatmid = treatmid_rep1,
                               treathigh = treathigh_rep1,
                                replID = "repl.1" 
                              )


image_data_rep2 <- data.frame( time = time_repl2, 
                                control =  control_rep2,
                              treatlow =  treatlow_rep2,
                              treatmid = treatmid_rep2,
                              treathigh = treathigh_rep2,
                                replID = "repl.2" 
                              )

image_data_rep3 <- data.frame( time = time_repl3, 
                                control =  control_rep3,
                               treatlow = treatlow_rep3,
                               treatmid = treatmid_rep3,
                               treathigh = treathigh_rep3,
                                replID = "repl.3" 
                              )

image_data <- rbind( image_data_rep1, image_data_rep2, image_data_rep3)

image_data.l <- melt( image_data, id.vars = c("time", "replID"), variable.name = "treatment")

plotFun <-function( Data , plotName ) {
  p <- ggplot( data = Data, aes( x = time, y = value )) + geom_point( aes(  color = replID), size = 6 ) +
    theme_minimal(base_size = 55) + ylim(c(-0.1,1.1)) + facet_grid( treatment~.) + 
    geom_smooth( aes( group = replID, color = replID  ) , span = 0.5,  se = FALSE, size = 1, alpha = 0.01) 
     
  png(paste("figures/",plotName, ".png", sep = ""), width = 1200, height = 1600)
    print( p )
dev.off()

}


# raw data
plotFun( Data = image_data.l, plotName = "rawdata")

# plate with unhappy cells

image_data.l<- as.data.table(image_data.l)

plotFun( Data = image_data.l[ replID == "repl.1"], plotName = "rawdata_unhappy")

plotFun( Data = image_data.l[ replID == "repl.2"], plotName = "rawdata_normal")

plotFun( Data = image_data.l[ replID == "repl.3"], plotName = "rawdata_highoutlier")



# linear normalization mean:

image_data.l <- as.data.table(image_data.l)

plateMeans <- image_data.l[, mean( value ), by = "replID"]

image_data.l[  , meanShift :=  value ]
image_data.l[ replID == "repl.1" , meanShift := value + ( plateMeans$V1[2] - plateMeans$V1[1] ) ]  
image_data.l[ replID == "repl.3" , meanShift := value + ( plateMeans$V1[2] - plateMeans$V1[3] )   ]

head(image_data.l)

image_data.meanshift <- melt( image_data.l, id.vars = c("time", "replID", "treatment"))
image_data.meanshift 

# define plotting function for extra side panel with normalized values
plotFunNorm <-function( Data , plotName ) {
  p <- ggplot( data = Data, aes( x = time, y = value )) + geom_point( aes(  color = replID), size = 6 ) +
    theme_minimal(base_size = 55)  + facet_grid( treatment~variable) + 
    geom_smooth( aes( group = replID, color = replID  ) , span = 0.5,  se = FALSE, size = 1, alpha = 0.01) 
     
  png(paste( "figures/",plotName, ".png", sep = ""), width = 1200, height = 1600 )
    print( p )
dev.off()

}

plotFunNorm( Data =  image_data.meanshift, plotName = "meanShift" )

# standard normal normalization (transformation to Z-score):

image_data.l[, meanShift:=NULL]
image_data.l[ , plateMean := mean( value ), by = replID]
image_data.l[ , plateSd := sd( value ), by = replID]
image_data.l[ , standardNormal := ( value - plateMean )/ plateSd , by = replID]
image_data.l[, plateMean := NULL ]
image_data.l[ , plateSd := NULL ]
image_data.sdNorm <- melt( image_data.l, id.vars = c("time", "replID", "treatment"))

plotFunNorm( Data = image_data.sdNorm, plotName = "standardNormalized")

image_data.l[, standardNormal:=NULL]


# control background subtraction

controlMeans <- image_data.l[ treatment == "control" ,  mean( value ), by = replID  ]
setkey( controlMeans, replID )
setkey( image_data.l, replID )
image_data.controlSub <- controlMeans[ image_data.l ]
image_data.controlSub[ , controlSubValue := value - V1 ]
image_data.controlSub[, V1 :=NULL ]
image_data.controlSub <- melt( image_data.controlSub, id.vars = c( "time", "replID", "treatment" ) )

plotFunNorm( Data = image_data.controlSub, plotName = "controlSub" )


# min max normalization

minmaxFun <- function(x) { 
                          min_e = min( x, na.rm = TRUE )
                          max_e = max( x, na.rm = TRUE )
                          y <- ( x - min_e ) / ( max_e - min_e )
                          y
                          }


image_data.l[,  minmaxNorm := minmaxFun( value ), by = replID ]
image_data.minmaxNorm <- melt( image_data.l, id.vars = c("time", "replID", "treatment"))
plotFunNorm( Data = image_data.minmaxNorm , plotName = "minmaxNorm")
image_data.l[ , minmaxNorm := NULL ]



# fold change with respect to control normalization
buffer <- image_data.l[ treatment == "control" ,  value, by = list( replID, time ) ]
controlValues <- buffer[ time %in% c(0.5, 0.8 ), value  , by = replID]
setkey(image_data.l, replID)
setkey( controlValues, replID)
foldChangeNorm <- controlValues[ image_data.l]

foldChangeNorm[ , foldChangeVal := i.value / value]
foldChangeNorm[, value := NULL]
setnames(foldChangeNorm, "i.value", "value")
foldChangeNorm <- melt( foldChangeNorm, id.vars = c("time", "replID", "treatment"))
plotFunNorm( Data =  foldChangeNorm, plotName = "foldChangeVal")





# non linear normalization
# sigmoid


sigmoidFun <- function(x, A, B) { 
                          y <-   1 / ( 1 + exp( - ( ( x - B ) / A  ) ) ) 
                          y
                          }

image_data.l$splitL <- NULL
image_data.l[,  sigmoidNorm := sigmoidFun( value, A = 0.07, B = 0.3 ), by = replID ]
image_data.sigmoidNorm <- melt( image_data.l, id.vars = c("time", "replID", "treatment"))

plotFunNorm( Data = image_data.sigmoidNorm , plotName = "sigmoidNorm")
image_data.l[ , sigmoidNorm := NULL ]





image_data.l<- as.data.table(image_data.l)
# quantile normalization
image_data.l[ , splitL := paste(treatment, replID)]
image_data.list <- split( image_data.l, image_data.l$splitL )


image_data.l[, .N, by = list( treatment,  replID ) ] # replicates have different time sampling. modeling required

require(splines)
model.results= list()
# first fitting and resampling of time points

for( i in seq_along(image_data.list)){
  
  fm1 <- lm(value ~ ns(time, df =6), data = image_data.list[[i]])
  
    model.results[[i]] <-  predict(fm1, dtTime<-data.frame(
    time = round(seq(0 , 24 , length.out=200), digits=2)))
    model.results[[i]] <- as.data.frame(model.results[[i]] )
    colnames(model.results[[i]])<- "mod"
   
    model.results[[i]]$treatment <- unique(image_data.list[[i]]$treatment)
    model.results[[i]]$replID <- unique(image_data.list[[i]]$replID)
    model.results[[i]]$time <- dtTime$time
    model.results[[i]]$resid.SD <- sqrt(deviance(fm1)/df.residual(fm1))
   
 

}


model.results.df <- do.call("rbind", model.results)

### quantile stats / fit

model.results.df <- as.data.table( model.results.df)


head(model.results.df)
head(image_data.l)

# plot fit + raw 

p <- ggplot( data = image_data.l, aes( x = time, y = value )) + geom_point(  size = 6 , aes( color = replID)) +
    theme_minimal(base_size = 55)  + facet_wrap( ~treatment ) + 
   geom_line( data = model.results.df, aes( x = time ,y = mod, group = replID, color = replID), size= 3 ) 
   
  png(paste( "figures/", "ns_fit", ".png", sep = ""), width = 1200, height = 1600 )
    print( p )
dev.off()

```
#downsample


```{r equal time sampling, echo = FALSE }

selTP <- unique(model.results.df[, time])[seq(1,  200, by = 8)]

model.results.df <- model.results.df[ time %in% selTP]

model.results.df[, .N, by = list(treatment, replID)]

table(model.results.df$treatment)

```


```{r, echo = FALSE}

quantileOrigList <- split(model.results.df, model.results.df$replID)
 # sort per plate

head(quantileOrigList[[1]])

quantileOrigIndex <- lapply(quantileOrigList, function(x) rank( x$mod ) )

quantileSorted <- lapply( quantileOrigList, function(x) sort(x$mod))
head(cbind(quantileSorted[[1]][quantileOrigIndex[[1]]] ,quantileOrigList[[1]])  )


quantileSorted.df <- do.call('cbind', quantileSorted)
newValues <- rowMeans(quantileSorted.df)
plot(newValues)


# put values back to original locations

for( i in seq_along(quantileOrigList)) {

  quantileOrigList[[i]]$quantileNorm <- newValues[quantileOrigIndex[[i]]]
  
  }

model.results.df <- do.call('rbind', quantileOrigList)

quantileNorm <- melt( model.results.df, id.vars = c("time", "replID", "treatment", "resid.SD"))
plotFunNorm( Data =  quantileNorm, plotName = "quantileNorm")

limits <- aes(ymax = value + resid.SD, ymin = value - resid.SD)

 # extra plot with error bars
p <- ggplot( data = quantileNorm, aes( x = time, y = value )) + geom_point( aes(  color = replID), size = 6 ) +
    theme_minimal(base_size = 55)  + facet_grid( treatment~variable) + 
   geom_errorbar( limits , size = 2 ) +
    geom_smooth( aes( group = replID, color = replID  ) , span = 0.5,  se = FALSE, size = 1, alpha = 0.01) 
     
  png(paste( "figures/","quantileNorm_errorbar", ".png", sep = ""), width = 1200, height = 1600 )
    print( p )
dev.off()

```



```{r statistics, echo = FALSE }
## statistics

# need sd over replicates for treatments:
model.results.df.sd <- model.results.df[ , sd( quantileNorm ), by = list( treatment , time)]

setnames(model.results.df.sd, "V1", "treat.sd")

DMSO <- model.results.df[ treatment %in% "control"]
 
# mean and sd for control
DMSO.s <- DMSO[ ,  list( DMSO.mean = mean( quantileNorm ), DMSO.sd = sd( quantileNorm ) ),  
                  by = list( treatment, time) ]

setkey(model.results.df, time)
setkey(DMSO.s, time)


model.results.df.stats <- DMSO.s[ model.results.df ] 

setkey(model.results.df.sd,  treatment,  time )
setkey(model.results.df.stats,  treatment, time )

model.results.df.stats <- model.results.df.sd[model.results.df.stats]

model.results.df.stats[ , meanDiff :=  abs(quantileNorm - DMSO.mean)  / sqrt ( ( DMSO.sd^2 + treat.sd^2 + resid.SD^2 ))  ]  # adding variances for total sd


Stats.m <- model.results.df.stats[, mean(meanDiff), by = list( i.treatment, replID  )]

setnames(Stats.m, "V1", "meanDiff")

stats.out = alist()
stats.out.data = alist()
stats.out.data[[1]] <- data.frame(  treatment = NA, fstatistic = NA, pVal = NA  )   
all.vars <- unique(Stats.m$i.treatment)
all.vars <- all.vars[ all.vars != "control"]
for( i in seq_along( all.vars )) {
 
  cur.treat <-as.character( unique( Stats.m[  i.treatment %in% all.vars[ i ], i.treatment ] ) )
  subSet1 <- Stats.m[ i.treatment %in% all.vars[ i ] ]
  subSetDMSO <- Stats.m[ i.treatment %in% "control" ]
  
  subSet <- rbind( subSetDMSO, subSet1)
  
    # one sided significance test
  subSet[ , i.treatment := factor(i.treatment, levels = c( "control", cur.treat ))]
  #setnames(subSet, "V1", "meanDiff")
  stats.out[[i]] <- t.test(meanDiff ~ i.treatment, alternative = "less", var.equal = TRUE, data =   subSet)
  
  m.out<- stats.out[[i]] 

  
  
    stats.out.data[[i]] <- data.frame(treatment = unique(subSet1$i.treatment),
                                    diffMeans = m.out$estimate[2] - m.out$estimate[1], 
                                    pVal = m.out$p.value)

}

stats.out.data.df <- do.call('rbind', stats.out.data)


require(plyr)

model.results.df.m <- ddply(model.results.df, .( treatment,  time),
      summarize, meanQ = mean(quantileNorm, na.rm = TRUE))


stats.out.data.df <- as.data.table(stats.out.data.df)
model.results.df.m <- as.data.table(model.results.df.m)

setkey(model.results.df.m,  treatment )
setkey(stats.out.data.df, treatment)
model.results.df.m.stat <- stats.out.data.df[model.results.df.m]


stats.out.data.df[ pVal > 0.1 , pval := ""]
stats.out.data.df[ pVal <= 0.1 , pval := "*"]
stats.out.data.df[ pVal <= 0.05 , pval := "**"]
stats.out.data.df[ pVal <= 0.01 , pval := "***"]

stats.out.data.df[, yloc := 0.7]


png(paste("figures", "/timecourses_1sided_sd3SUM_quantile.png", sep =""), height = 1200, width = 1600)
p<-ggplot( model.results.df.m, aes(x=time, y = meanQ ) ) +
  geom_point( size = 6) + theme_minimal( base_size = 40)
p <- p +  facet_wrap( ~treatment)
p <- p +  geom_text( data = stats.out.data.df, 
                     aes(x = 4, y =yloc, label =  pval ), size = 40) +
   geom_text( data = stats.out.data.df, 
                     aes(x = 4, y =yloc + 0.2, label =  round( pVal, digits = 4) ), size = 12) 


print(p)
dev.off()






```

